[feature/161-orders-get] 주문 상세 조회 api
Kek-i/KEKI_Server pull request #174
Opened 2023-03-10 15:20 UTC by chaerlo127

## 📚 이슈 번호
#161 

## 💬 기타 사항
- TODO 를 봐주세요,,!

2023-03-10 15:37 UTC, psyeon1120 approved these changes
👍 👍

2023-03-10 15:40 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/order/controller/OrderController.java
> +     * 주문 상세 조히 API
어쩌다 오타 발견 ㅎㅅㅎ

2023-03-10 15:42 UTC, JoongHyun-Kim commented on src/main/java/com/codepatissier/keki/order/controller/OrderController.java
> +     * 주문 상세 조히 API
상세 조히~

2023-03-10 15:43 UTC, JoongHyun-Kim approved these changes
✨👍

2023-03-10 15:43 UTC, JoongHyun-Kim commented on src/main/java/com/codepatissier/keki/order/service/OrderService.java
> +        User user = userRepository.findByUserIdxAndStatusEquals(userIdx, ACTIVE_STATUS).orElseThrow(() -> new BaseException(INVALID_USER_AND_STATUS));
빼는거 조아요!

2023-03-10 15:46 UTC, sojungpp requested changes
넘수고하셨슴다-! ❤️‍🔥

2023-03-10 15:46 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/order/dto/GetOrder.java
> +    String storeAccount;
이거 이름이랑 계좌번호 같이 받기로 했었던 것 같은디,, 생각해보니까 나누는 것도 괜찮을 것 같고 뭐가 좋을까 샘들

2023-03-10 15:46 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/order/service/OrderService.java
> +        // TODO: 겹치는 부분이 3줄 이상인데 extract method 는 어떠신지?
대찬성임다

2023-03-10 15:46 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/order/service/OrderService.java
> +        // TODO: 아직 판매자 계좌 번호는 DB에 없는 건가요?
어 이거 그래서 위에 물어봤는데 머가 좋을까용

2023-03-10 15:47 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/order/dto/GetOrder.java
> +    String storeAccount;
@chaerlo127 @psyeon1120 @JoongHyun-Kim

2023-03-11 12:10 UTC, JoongHyun-Kim commented on src/main/java/com/codepatissier/keki/order/dto/GetOrder.java
> +    String storeAccount;
난 따로 받는게 좋을 것 같아유

2023-03-11 12:21 UTC, psyeon1120 commented on src/main/java/com/codepatissier/keki/order/dto/GetOrder.java
> +    String storeAccount;
따로가 좋을 것 같아용

2023-03-11 12:22 UTC, JoongHyun-Kim commented on src/main/java/com/codepatissier/keki/order/dto/GetOrder.java
> +    String storeAccount;
아 근데 저희 판매자가 설정한 예금주명이랑 진짜 계좌의 예금주명을 검증할 방법은 없죠??

2023-03-11 12:24 UTC, psyeon1120 commented on src/main/java/com/codepatissier/keki/order/service/OrderService.java
> +        User user = userRepository.findByUserIdxAndStatusEquals(userIdx, ACTIVE_STATUS).orElseThrow(() -> new BaseException(INVALID_USER_AND_STATUS));
좋아요!

2023-03-11 12:27 UTC, psyeon1120 commented on src/main/java/com/codepatissier/keki/order/dto/GetOrder.java
> +    String storeAccount;
계좌실명조회 Open API가 있긴합니다!

2023-03-11 13:27 UTC, sojungpp approved these changes

2023-03-11 15:57 UTC, merged