[feature/12-posts-getposts] 스토어별 피드 목록 조회 API
Kek-i/KEKI_Server pull request #20
Opened 2023-01-12 08:25 UTC by psyeon1120

## 📚 이슈 번호
#12

## 💬 기타 사항
- [ ] PostService에서 orElseThrow 다시 해보기

2023-01-12 14:27 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
> +    // posts(2200~2299)
정리감사합니다,,✨

2023-01-12 14:32 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/post/controller/PostController.java
> +            return new BaseResponse<>(e.getStatus());
혹시 cursorIdx는 어떤걸 의미하는걸까요 ?!!

2023-01-12 14:34 UTC, psyeon1120 commented on src/main/java/com/codepatissier/keki/post/service/PostService.java
> +                    .orElseThrow(() -> new BaseException(INVALID_STORE_IDX));
여기서 `orElseThrow`로 `INVALID_STORE_IDX` 오류로 설정했는데 결국 밑에 `throw new BaseException(BaseResponseStatus.DATABASE_ERROR);`로 나와요ㅠㅠ 해결방법 아시는분...?

2023-01-12 14:36 UTC, psyeon1120 commented on src/main/java/com/codepatissier/keki/post/controller/PostController.java
> +            return new BaseResponse<>(e.getStatus());
페이징 할때 필요한건데 현재까지 로딩된 피드 idx 입니당
cursorIdx가 있으면 해당 피드 다음것부터 새로 로딩하는 거예요!

2023-01-12 14:38 UTC, sojungpp requested changes
넘넘 수고하셨슴니다 체고🤩✨

2023-01-12 14:38 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/post/dto/GetStorePostsRes.java
> +    }
이 부분 혹시 피드가 맞다면 혹시 Item 말고 다른 네이밍은 어떨까요..!
그 디저트 부분이 상품이라고 생각되어서 한 번 말해봅니당

2023-01-12 14:41 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/post/service/PostService.java
> +                    .orElseThrow(() -> new BaseException(INVALID_STORE_IDX));
으음 멀까 storeIdx 있을 때는 데이터베이스 오류 따로 안 뜨나요?!

2023-01-12 14:45 UTC, psyeon1120 commented on src/main/java/com/codepatissier/keki/post/service/PostService.java
> +                    .orElseThrow(() -> new BaseException(INVALID_STORE_IDX));
올바른 값이 들어가면 오류 안나는데 일부러 이상한 값 넣어보면 `INVALID_STORE_IDX`로 설정이 됐다가 `DATABASE_ERROR` 다시 설정돼서 나와용
아마 catch에서 throw new 를 해서 그런것 같은데 저 방법말고 다른 방법이 있을까요?

2023-01-12 14:51 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/post/service/PostService.java
> +                    .orElseThrow(() -> new BaseException(INVALID_STORE_IDX));
`if(~=null) throw new BaseException(INVALID_STORE_IDX);` 이런 방법,,? 원인이 뭔지 잘 모르겠어서 되려나 잘 모르겠슴다ㅠㅡ

2023-01-12 14:53 UTC, JoongHyun-Kim commented on src/main/java/com/codepatissier/keki/post/service/PostService.java
> +                    .orElseThrow(() -> new BaseException(INVALID_STORE_IDX));
저도 이거 똑같은 부분 고치는 중인데 findById 반환값이 Optional이라서 그렇다는 것 같아요,,
https://velog.io/@hnsoo/JPA-%EC%9E%98%EB%AA%BB%EB%90%9C-%ED%91%9C%ED%98%84-OptionalListobject

2023-01-12 14:53 UTC, JoongHyun-Kim commented on src/main/java/com/codepatissier/keki/post/service/PostService.java
> +                    .orElseThrow(() -> new BaseException(INVALID_STORE_IDX));
맞는지 모르겠습니다,,

2023-01-12 14:55 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/post/controller/PostController.java
> +            return new BaseResponse<>(e.getStatus());
오옹 나중에 노션 명세서에 한 번만 작성 부탁드려요 !!

2023-01-12 15:30 UTC, psyeon1120 commented on src/main/java/com/codepatissier/keki/post/service/PostService.java
> +                    .orElseThrow(() -> new BaseException(INVALID_STORE_IDX));
저랑 약간 다른 상황인것 같아요..ㅜㅜ 다른 방법으로 했습니다!!

2023-01-12 15:32 UTC, sojungpp approved these changes

2023-01-12 15:35 UTC, JoongHyun-Kim commented on src/main/java/com/codepatissier/keki/post/service/PostService.java
> +                    .orElseThrow(() -> new BaseException(INVALID_STORE_IDX));
짱!!

2023-01-12 15:36 UTC, JoongHyun-Kim approved these changes
완전 수고하셨습니당~!!!💛

2023-01-12 15:41 UTC, JoongHyun-Kim commented on src/main/java/com/codepatissier/keki/post/service/PostService.java
> +                    .orElseThrow(() -> new BaseException(INVALID_STORE_IDX));
슨생님,,저도 같은 방법으로 고쳤습니다,,감사합니다,,

2023-01-13 04:31 UTC, chaerlo127 approved these changes
🌱🍀🌱

2023-01-13 05:27 UTC, merged