[feature/1-infra] 프로젝트 초기 설정
Kek-i/KEKI_Server pull request #3
Opened 2023-01-06 15:20 UTC by chaerlo127

## 📚 이슈 번호
#1 

## 💬 기타 사항
- none

2023-01-06 15:30 UTC, sojungpp requested changes
enum 변환하는거 변수명만 바꿔주면 좋을 것 같아용
암호화 진자 최고-🫶

2023-01-06 15:30 UTC, sojungpp commented on src/main/java/com/example/keki/common/Role.java
> +    public static Role getContractStatusByNum(int number){
이거 변수명 한 번만 바꿔주세요!

2023-01-06 15:30 UTC, sojungpp commented on src/main/java/com/example/keki/common/Role.java
> +    public static Role getContractStatusByName(String name){
여기두용

2023-01-06 15:30 UTC, sojungpp commented on src/main/java/com/example/keki/calendar/CalendarCategory.java
> +    public static CalendarCategory getContractStatusByNum(int number){
"

2023-01-06 15:30 UTC, sojungpp commented on src/main/java/com/example/keki/calendar/CalendarCategory.java
> +    public static CalendarCategory getContractStatusByName(String name){
"

2023-01-06 15:39 UTC, sojungpp approved these changes
엄청 빠르시네요 선생님 고생하셨슴다-!

2023-01-06 15:54 UTC, psyeon1120 commented
전체 패키지이름이 example인데 혹싀 변경하는건 어떨까요? 팀명같은걸루요... :)

2023-01-07 04:07 UTC, JoongHyun-Kim commented
혹시 stores도 따로 빼는거 맞을까요??

2023-01-07 04:55 UTC, chaerlo127 commented
> 혹시 stores도 따로 빼는거 맞을까요??

@JoongHyun-Kim stores를 하위 package로 생성하는 거 말씀이신가용??

2023-01-07 04:57 UTC, JoongHyun-Kim commented
> > 혹시 stores도 따로 빼는거 맞을까요??
> 
> @JoongHyun-Kim stores를 하위 package로 생성하는 거 말씀이신가용??

네네!

2023-01-07 06:57 UTC, psyeon1120 approved these changes
👍

2023-01-07 06:59 UTC, JoongHyun-Kim approved these changes

2023-01-07 06:59 UTC, JoongHyun-Kim commented on src/main/java/com/codepatissier/keki/stores/controller/StoreController.java
> +package com.codepatissier.keki.stores.controller;
패키지명 수정이랑 stores 폴더 생성 모두 확인했습니다~!! 완전 수고 많으셨어요!!! 짱❤️‍🔥

2023-01-07 07:02 UTC, merged