[feature/10-calendars-token-fix] token api로 접근
Kek-i/KEKI_Server pull request #45
Opened 2023-01-18 07:42 UTC by chaerlo127

## 📚 이슈 번호
#10

## 💬 기타 사항
- none

2023-01-18 12:22 UTC, sojungpp requested changes

2023-01-18 12:22 UTC, sojungpp commented on src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
> +    @PatchMapping("/{calendarIdx}/users")
혹시 API 명세서에 calendars/{calendarIdx} 로 되어있어서 여쭤보는데 뒤에 users를 붙이는 이유가 있을까요?!

2023-01-18 14:15 UTC, chaerlo127 commented on src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
> +    @PatchMapping("/{calendarIdx}/users")
@sojungpp 
아 오타에여 내일 고칠게요
진심.. 님 최고❤️

2023-01-19 05:27 UTC, sojungpp approved these changes

2023-01-19 05:28 UTC, JoongHyun-Kim approved these changes

2023-01-19 05:28 UTC, psyeon1120 approved these changes

2023-01-19 05:29 UTC, merged